import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CraftingWorkbench } from '@/components/crafting/CraftingWorkbench';
import { recipes } from '@/data/recipes';
import { findItem } from '@/data/items';
export const CraftingPage = () => {
    return (_jsxs("section", { className: "crafting-page", children: [_jsxs("header", { className: "crafting-page__intro", children: [_jsx("h1", { children: "Crafting Workbench" }), _jsx("p", { children: "Experiment with inputs, tools, and tribe members to discover the perfect recipe. The prototype below mirrors the in-game workbench layout so we can test UX flows and capture visual baselines for the art team." })] }), _jsx(CraftingWorkbench, {}), _jsxs("section", { className: "crafting-page__recipes", "aria-labelledby": "recipe-list-heading", children: [_jsxs("div", { className: "crafting-page__recipes-header", children: [_jsx("h2", { id: "recipe-list-heading", children: "Reference Recipes" }), _jsx("p", { children: "These reference cards help verify the crafting data driving the workbench mockup. Once the simulation is interactive we can wire the tray to these recipes directly." })] }), _jsx("div", { className: "card-grid", children: recipes.map((recipe) => (_jsxs("article", { className: "card", "aria-labelledby": `${recipe.id}-title`, children: [_jsx("h3", { id: `${recipe.id}-title`, children: recipe.name }), _jsxs("p", { children: ["Unlocks at camp tier ", recipe.unlockedAtLevel, "."] }), _jsx("ul", { children: recipe.ingredients.map((ingredient) => {
                                        const item = findItem(ingredient.itemId);
                                        return (_jsxs("li", { children: [ingredient.quantity, "x ", item?.name ?? ingredient.itemId] }, ingredient.itemId));
                                    }) }), _jsxs("p", { children: ["Output: ", recipe.output.quantity, "x", ' ', findItem(recipe.output.itemId)?.name ?? recipe.output.itemId] })] }, recipe.id))) })] })] }));
};
//# sourceMappingURL=CraftingPage.js.map